# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'manikondanikhil@gmail.com'
url:                 ''
baseurl:             ''
blogurl:             '/blog'
paginate:            5
plugins:
  - jekyll-paginate
# About/contact 
author:
  name:              Nikhil Manikonda
  url:               https://twitter.com/mdo
  email:             manikondanikhil@gmail.com

# Custom vars
version:             1.0.0


